# The Site Configuration

# Import the theme
theme: jekyll-theme-chirpy

# The language of the webpage › http://www.lingoes.net/en/translator/langcode.htm
# If it has the same name as one of the files in folder `_data/locales`, the layout language will also be changed,
# otherwise, the layout language will use the default value of 'en'.
lang: en

# Change to your timezone › https://kevinnovak.github.io/Time-Zone-Picker
timezone: America/Chicago

# jekyll-seo-tag settings › https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
# ↓ --------------------------

title: The NSITE Participant Dashboard # the main title

tagline: Assisting SNWG Solution Implementation teams hroughout the Solution Project lifecycle  # it will display as the sub-title

description: >- # used by seo meta and the atom feed
  A minimal, responsive website explaining the base need-to-know information for project selected and funded by the Satellite Needs Working Group.

# Fill in the protocol & hostname for your site.
# e.g. 'https://username.github.io', note that it does not end with a '/'.
url: "https://nasa-impact.github.io"

github:
  username: CherrelleTucker # change to your github username

twitter:
  username: SNWG on EarthData|IMPACT # change to your twitter username

social:
  # Change to your full name.
  # It will be displayed as the default author of the posts and the copyright owner in the Footer
  name: SNASA's SNWG Implementation Team
  email: cherrelle.j.tucker@nasa.gov # change to your email address
  links:
    # The first element serves as the copyright owner's link
    - https://impact.earthdata.nasa.gov/project/snwg.html#:~:text=NASA%20has%20established%20an%20SNWG,NASA%20to%20meet%20those%20needs. # change to your twitter homepage
    - https://github.com/username # change to your github homepage
    # Uncomment below to add more social links
    - https://www.earthdata.nasa.gov/esds/impact/snwg/sep#:~:text=NASA%27s%20SNWG%20SEP%20efforts%20include,products%20for%20stakeholder%20decision%2Dmaking
    # - https://www.linkedin.com/in/username

# Site Verification Settings
webmaster_verifications:
  google: # fill in your Google verification code
  bing: # fill in your Bing verification code
  alexa: # fill in your Alexa verification code
  yandex: # fill in your Yandex verification code
  baidu: # fill in your Baidu verification code
  facebook: # fill in your Facebook verification code

# ↑ --------------------------
# The end of `jekyll-seo-tag` settings

# Web Analytics Settings
analytics:
  google:
    id: # fill in your Google Analytics ID
  goatcounter:
    id: # fill in your GoatCounter ID
  umami:
    id: # fill in your Umami ID
    domain: # fill in your Umami domain
  matomo:
    id: # fill in your Matomo ID
    domain: # fill in your Matomo domain
  cloudflare:
    id: # fill in your Cloudflare Web Analytics token

# Pageviews settings
pageviews:
  provider: # now only supports 'goatcounter'

# Prefer color scheme setting.
#
# Note: Keep empty will follow the system prefer color by default,
# and there will be a toggle to switch the theme between dark and light
# on the bottom left of the sidebar.
#
# Available options:
#
#     light  - Use the light color scheme
#     dark   - Use the dark color scheme
#
theme_mode: light

# The CDN endpoint for media resources.
# Notice that once it is assigned, the CDN url
# will be added to all media resources (site avatar, posts' images, audio and video files) paths starting with '/'
#
# e.g. 'https://cdn.com'
cdn:

# the avatar/profile pic on sidebar 
avatar: assets/img/avatar/profile.png

# The URL of the site-wide social preview image used in SEO `og:image` meta tag.
# It can be overridden by a customized `page.image` in front matter.
social_preview_image: # string, local or CORS resources

# boolean type, the global switch for TOC in posts.
toc: true

comments:
  # Global switch for the post comment system. Keeping it empty means disabled.
  provider: # [disqus | utterances | giscus]
  # The provider options are as follows:
  disqus:
    shortname: # fill with the Disqus shortname. › https://help.disqus.com/en/articles/1717111-what-s-a-shortname
  # utterances settings › https://utteranc.es/
  utterances:
    repo: # <gh-username>/<repo>
    issue_term: # < url | pathname | title | ...>
  # Giscus options › https://giscus.app
  giscus:
    repo: # <gh-username>/<repo>
    repo_id:
    category:
    category_id:
    mapping: # optional, default to 'pathname'
    strict: # optional, default to '0'
    input_position: # optional, default to 'bottom'
    lang: # optional, default to the value of `site.lang`
    reactions_enabled: # optional, default to the value of `1`

# Self-hosted static assets, optional › https://github.com/cotes2020/chirpy-static-assets
assets:
  self_host:
    enabled: # boolean, keep empty means false
    # specify the Jekyll environment, empty means both
    # only works if `assets.self_host.enabled` is 'true'
    env: # [development | production]

pwa:
  enabled: true # the option for PWA feature (installable)
  cache:
    enabled: true # the option for PWA offline cache
    # Paths defined here will be excluded from the PWA cache.
    # Usually its value is the `baseurl` of another website that
    # shares the same domain name as the current website.
    deny_paths:
      # - "/example"  # URLs match `<SITE_URL>/example/*` will not be cached by the PWA

#paginate: 10

# The base URL of your site not including a trailing slash.
baseurl: "/SNWG-Participant-Dashboard" # change to your site's base URL

# ------------ The following options are not recommended to be modified ------------------

kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts: # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

# Default Settings for Jekyll Site
# These settings determine the default behavior for different types of content

defaults:
  # Default settings for all files
  - scope:
      path: "" # An empty string here means all files in the project
      type: pages
    values:
      layout: page
      comments: false
      toc: true
      permalink: /:title/

  # Specific settings for home page/index
  - scope:
      path: "index.md"
    values:
      layout: page
      permalink: /
      toc: false
      comments: false

  # Settings for blog posts
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/

  # Settings for tag pages
  - scope:
      path: ""
      type: tags
    values:
      layout: tag
      permalink: /tags/:name/

  # Settings for category pages
  - scope:
      path: ""
      type: categories
    values:
      layout: category
      permalink: /categories/:name/

  # Settings for draft posts
  - scope:
      path: "_drafts"
    values:
      layout: post
      comments: false
      toc: true

  # Settings for tab pages
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/
      dynamic_title: true # Enable dynamic titles

  # Settings for assets
  - scope:
      path: "assets/js/dist"
    values:
      swcache: true

  # Settings for special pages
  - scope:
      path: "404.html"
    values:
      layout: page
      permalink: /404.html
      toc: false
      comments: false

  # Settings for archive pages
  - scope:
      path: "archives.html"
    values:
      layout: page
      permalink: /archives/
      toc: false

sass:
  style: compressed
#  sass_dir: _sass

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]


exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - "*.config.js"
  - package*.json

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tags: /tags/:name/
    category: /categories/:name/

# added to customize the theme

plugins:
  - jekyll-data # Ensure Jekyll processes _data files
  - jekyll-paginate # Ensure Jekyll processes pagination
  - jekyll-archives # Ensure Jekyll processes archives
  - jekyll-tags # Ensure Jekyll processes tags
  
# The directory to store the layouts.
layouts_dir: _layouts

# paginate_path: /page:num/

# Sidebar Settings
sidebar:
  enabled: true
  data_source: navigation.yml # Points to the file in _data

# URL settings
relative_url: true # enable relative urls
permalink: /:title/ # leading slash since baseurl has no trailing slash
